(WIP) run backend trigger validation before saving
moira-alert/web2.0 pull request #358
Opened 2022-07-08 05:38 UTC by sol-un

https://yt.skbkontur.ru/issue/MOIRA-168
https://yt.skbkontur.ru/issue/MOIRA-174

2022-07-11 05:52 UTC, dimohqa99 commented
Код с `getAsyncValidator`, `handleSubmit` и `onChange` повторяется 3 раза. Подумай как это можно исправить. Сходу накидываю вариант: вынести на более высокий уровень (контейнер для трех компонентов, который управляет состоянием и валидацией).

2022-07-11 05:59 UTC, dimohqa99 commented
Еще `getAsyncValidator`  нужен для того, чтобы когда функция на чек изменилась не вызвался колбэк. Судя по коду прокидывается все время один и тот же check из MoiraApi, который не меняется. Я бы выпилил этот код.

2022-07-11 06:07 UTC, dimohqa99 commented
Еще один вариант: объединить все 3 компонента контейнера в один, если они одинаковые. Желательно сначала тут аргументировать какой из вариантов хочешь сделать

2022-07-13 11:25 UTC, dimohqa99 requested changes

2022-07-13 11:45 UTC, dimohqa99 requested changes
Посмотрел функ компонент TriggerAddContainer. Поправь замечания и приступай к TriggerEditContainer

2022-07-13 11:45 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +            return;
Давай перед return оставлять пустую строчку, так проще код читать

2022-07-13 11:45 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +                    ...prevState,
Такие штуки надо превратить в 
```ts
setTrigger({ 
    ...trigger, 
    error_value: null, 
    warn_value: null 
});
```

2022-07-13 11:45 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +                    ...prevState,
Дальше по коду везде убрать prevState

2022-07-13 11:45 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +        const { moiraApi } = props;
Убрать

2022-07-13 11:45 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +        getData(props);
Нет смысла передавать props через аргументы, ты можешь напрямую обратиться к `props` в `getData`

2022-07-13 11:45 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +    }, [props]);
Там от props только moiraApi. Он судя по коду никогда не меняется, давай уберем props, чтобы делать выборку только при маунте компонента

2022-07-15 08:59 UTC, dimohqa99 requested changes

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +        const { moiraApi } = props;
Убрать, вроде уже писал мотивацию так не делать

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
>          const { moiraApi } = props;
Тоже самое

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerDuplicateContainer.tsx
> +        const { moiraApi } = props;
Убрать

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerDuplicateContainer.tsx
> +        }
После if лучше делать пустую строку. Так легче читать код потом

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerDuplicateContainer.tsx
> +        const { moiraApi } = props;
Убрать

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerEditContainer.tsx
> -    }
А что стало в итоге с этим кодом?

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerEditContainer.tsx
> +        }
Пустая строка после if

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerEditContainer.tsx
> +        const { moiraApi, history } = props;
Убрать

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerEditContainer.tsx
> +        const { moiraApi } = props;
Убрать

2022-07-15 08:59 UTC, dimohqa99 commented on src/Containers/TriggerEditContainer.tsx
> +        const { id } = props.match.params;
Id используется 1 раз, тоже убрать

2022-07-15 08:59 UTC, dimohqa99 commented on src/hooks/useTriggerFormContainer.tsx
> +            const validationResult = await moiraApi.validateTrigger(trigger);
Давай вынесем вызов валидации в отдельную функцию с try catch. Там же сделаем setValidationResult.
Вроде раньше такой код был, почему решил отказаться от него?

2022-07-18 08:13 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +function TriggerAddContainer(props: Props) {
`const TriggerAddContainer = (props: Props) => {`

2022-07-18 08:15 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +        setValidationResult(undefined);
А почему ты решил оставить сброс этих настроек?

2022-07-18 08:16 UTC, dimohqa99 commented on src/Containers/TriggerAddContainer.tsx
> +            props.moiraApi
Зачем здесь нужен проброс всего класса `moiraApi`? Передавай его при инициализации твоего хука

2022-07-20 04:47 UTC, dimohqa99 commented on src/tests/triggerCRUD.test.ts
> +        await expect(triggerViewPage.isOpen()).resolves.toEqual(false);
Я так понимаю тут приходит check с ошибкой? Тогда лучше что-то осмысленное проверять, а не проверку на открытие страницы. Например, найти текст ошибки

2022-07-20 04:48 UTC, dimohqa99 commented on src/tests/triggerCRUD.test.ts
> +    it(`edit trigger`, async () => {
Почему проверку на работу валидации не стал добавлять в форму редактирования?

2022-07-20 04:50 UTC, dimohqa99 commented on src/tests/core/controls/Input.ts
> +                control?.click({ clickCount: 3 });
Зачем 3 раза кликать?

2022-07-20 04:50 UTC, dimohqa99 commented on src/hooks/useTriggerFormContainer.tsx
> +            const validationResult = await moiraApi.validateTrigger(trigger);
Так и не поправил return

2022-07-21 05:44 UTC, sol-un commented on src/tests/core/controls/Input.ts
> +                control?.click({ clickCount: 3 });
Тройной клик по инпуту выделяет весь текст внутри него.

2022-07-21 09:54 UTC, dimohqa99 approved these changes

2022-07-21 10:00 UTC, merged