add confirmation dialog for trigger deletion
moira-alert/web2.0 pull request #359
Opened 2022-07-11 06:12 UTC by sol-un

Add a dialog to confirm trigger deletion from the trigger editing page.

2022-07-18 04:01 UTC, dimohqa99 commented on src/Containers/TriggerEditContainer.tsx
> +                                                <Modal width={600} noClose>
Вынеси модалку в отдельный компонент

2022-07-18 04:02 UTC, dimohqa99 commented on src/Containers/TriggerEditContainer.tsx
> +                                                        <strong>{` ${trigger.name} `}</strong>
Зачем пробелы перед и после?

2022-07-26 04:31 UTC, dimohqa99 requested changes

2022-07-26 04:31 UTC, dimohqa99 commented on package.json
> +        "test:e2e": "cross-env NODE_ENV=testing TYPE=e2e jest ./src/tests --runInBand --detectOpenHandles",
Зачем нужен этот ключ?

2022-07-26 04:31 UTC, dimohqa99 commented on src/Components/TriggerDeleteModal/TriggerDeleteModal.tsx
> +            Trigger {<strong>{props.triggerName}</strong>} will be deleted.
Зачем strong оборачивать в `{}`, в таких случаях лучше добавлять неразрывные пробелы nbsp;

2022-07-26 04:31 UTC, dimohqa99 commented on src/Components/TriggerDeleteModal/TriggerDeleteModal.tsx
> +                <Button onClick={props.onDelete} data-tid="Delete Trigger Modal Delete Button">
Может сократить `data-tid`, выглядит оч перегружено информацией

2022-07-26 04:31 UTC, dimohqa99 commented on src/tests/triggerCRUD.test.ts
> +    it("update trigger", async () => {
Почему update? Насколько я понимаю edit это редактирования информации, а update это добавление новой информации

2022-07-26 04:31 UTC, dimohqa99 commented on src/tests/triggerCRUD.test.ts
> +        ).rejects;
Зачем тестировать проверку, которая всегда должна не проходить? Обычно в тестах стараются не завязываться на такие кейсы. Лучше проверять на существование, чем на пустоту

2022-07-26 08:52 UTC, sol-un commented on package.json
> +        "test:e2e": "cross-env NODE_ENV=testing TYPE=e2e jest ./src/tests --runInBand --detectOpenHandles",
Без него Jest показывает предупреждение о незавершенных асинхронных процессах и предлагает его указать. Кажется, что кроме предупреждения это ни на что не влияет, поэтому удалил.

![Screenshot 2022-07-26 154130](https://user-images.githubusercontent.com/54800034/180965395-9cbfb452-6157-446f-89b7-a7b8421420ea.png)

2022-07-26 09:48 UTC, dimohqa99 commented on package.json
> +        "test:e2e": "cross-env NODE_ENV=testing TYPE=e2e jest ./src/tests --runInBand --detectOpenHandles",
https://jestjs.io/ru/docs/cli#--detectopenhandles
Пишут, что она существенно снижает производительность и рекомендуется только при отладке

2022-07-26 09:50 UTC, dimohqa99 approved these changes

2022-07-27 03:08 UTC, merged