simplify metric sorting & add test coverage
moira-alert/web2.0 pull request #365
Opened 2022-07-28 09:17 UTC by sol-un

2022-07-29 08:56 UTC, dimohqa99 requested changes

2022-07-29 08:56 UTC, dimohqa99 commented on src/helpers/sort-metrics.ts
> +    const sorterMap: SorterMap = {
Надо вынести этот Map за функцию, чтобы основной sortMetrics можно было быстро прочитать и понять что он делает

2022-07-29 08:56 UTC, dimohqa99 commented on src/helpers/sort-metrics.ts
> +            return stateA < stateB ? 1 : -1;
Одинаковая проверка еще в 2 местах ниже. Вынеси это в отдельную функцию в этом же файле

2022-07-29 08:56 UTC, dimohqa99 commented on src/helpers/sort-metrics.test.ts
> +        maintenance_info: {
Ненужное поле

2022-07-29 08:56 UTC, dimohqa99 commented on src/helpers/sort-metrics.test.ts
> +        suppressed: false,
Ненужное поле

2022-08-01 03:58 UTC, sol-un commented on src/helpers/sort-metrics.test.ts
> +        maintenance_info: {
Непосредственно для тестов эти поля не нужны, но все же функция `sortMetrics`, которую мы тестируем, ожидает на вход массив объектов типа `Metric`. Если удалить поля из тестовых данных, они не будут соответствовать этому типу.

2022-08-01 03:59 UTC, sol-un commented on src/helpers/sort-metrics.test.ts
> +        suppressed: false,
См. выше

2022-08-01 04:28 UTC, dimohqa99 commented on src/helpers/sort-metrics.ts
> +const compare = (argA: number | string, argB: number | string) => {
В таком варианте функции можно сюда передать в первом аргументе строку, а во втором число и наоборот.
Тут можно воспользоваться дженериками

2022-08-01 04:32 UTC, dimohqa99 commented on src/helpers/sort-metrics.ts
> +const sorterMap = {
Затипизируй объект

2022-08-01 07:12 UTC, dimohqa99 approved these changes

2022-08-01 07:42 UTC, merged