Feature/highlight clickable areas in list item
moira-alert/web2.0 pull request #390
Opened 2022-11-14 13:41 UTC by sol-un

# PR Summary

Change css to highlight more clearly the clickable areas in a trigger list item (state, data, and tags).

2022-11-15 10:13 UTC, dimohqa99 requested changes
Не увидел скриншотного теста на ховер тэга и средней области тригера. Или они есть?

2022-11-15 10:13 UTC, dimohqa99 commented on src/Components/TagGroup/TagGroup.less
> +    //margin-left: -5px;
Комментарии оставил с какой-то целью?

2022-11-15 10:13 UTC, dimohqa99 commented on src/Components/TagGroup/TagGroup.less
> +    //margin-left: 5px;
Тот же вопрос

2022-11-15 10:13 UTC, dimohqa99 commented on src/Components/TriggerListItem/TriggerListItem.less
> +    -webkit-mask-image: linear-gradient(
Проверь на всех браузерах, что это работает как надо

2022-11-15 10:13 UTC, dimohqa99 commented on src/Components/TriggerListItem/TriggerListItem.less
> -    }
Не понял почему этот код удалили. Там же только ховер должен был измениться

2022-11-15 10:13 UTC, dimohqa99 commented on src/Components/Tag/Tag.less
> +        filter: saturate(5);
Интересное решение. Не знал о такой фиче. Посмотрел поддержку браузеров, вообще огонь

2022-11-15 10:43 UTC, sol-un commented on src/Components/TriggerListItem/TriggerListItem.less
> -    }
История такая) Эти стили нужны были, чтобы сделать небольшой градиент в низу триггера, если у него длинный таргет:

![Screenshot 2022-11-15 082329](https://user-images.githubusercontent.com/54800034/201897706-6a65cc3d-5393-41a3-b6db-206c55447667.png)

Это было сделано за счет псевдоэлемента, раскрашенного градиентом из прозрачного в белый. Причем, если у тебя раскрыты метрики, то надо было его заменить на такой же псевдоэлемент, только с серым вместо белого:

2022-11-15 11:02 UTC, sol-un commented on src/Components/TriggerListItem/TriggerListItem.less
> +    -webkit-mask-image: linear-gradient(
Проверили на хроме, фф, сафари. Все норм работает

2022-11-15 11:10 UTC, sol-un commented on src/Components/TagGroup/TagGroup.less
> +    //margin-left: 5px;
Нет, они не нужны, удалил

2022-11-17 07:43 UTC, GreoGi commented on src/Components/TriggerListItem/TriggerListItem.less
> +    text-decoration: none !important;
Зачем тут ` text-decoration: none !important;`?
Если стиль ссылок перебить хотите, то попробуйте лучше вместо !important использовать селектор по типу
`.header a { ... }`, возможно его по специфичности хватит

2022-11-17 07:50 UTC, GreoGi commented on src/Components/TriggerListItem/TriggerListItem.less
>  }
```css
    -webkit-mask-repeat: no-repeat;
    -webkit-mask-size: 100% 80px;
    -webkit-mask-position: 0px -15px;
```

Добавь сюда ниже ещё те же свойства, но без вендор префикса `-webkit-`

2022-11-17 10:22 UTC, sol-un commented on src/Components/TriggerListItem/TriggerListItem.less
> +    text-decoration: none !important;
А черт его знает зачем) Убрал -- ничего не поменялось

2022-11-17 10:53 UTC, dimohqa99 approved these changes

2022-11-18 09:41 UTC, dimohqa99 approved these changes

2022-11-18 10:10 UTC, merged