readme update
moira-alert/web2.0 pull request #445
Opened 2023-10-23 12:50 UTC by EduardZaydler

# PR Summary
instruction to proxy to dev

2023-10-24 07:25 UTC, sol-un commented on README.md
> +For SKB Kontur developers only. Starts a dev server on port 9000 and proxies all API requests to 9002 port. Forward 9002 port to api Pod. The easiest way is to use [Lens](https://k8slens.dev/). Stagi
Немного поправим инглиш:
```suggestion
For SKB Kontur developers only. Starts a dev server on port 9000 and proxies all API requests to port 9002, which is forwarded to API Kubernetes pod. For the easiest way to use Lens, see: https://k8slens.dev/. The staging cluster config is [here](https://k8s.testkontur.ru/).
```

2023-10-24 07:27 UTC, sol-un requested changes
В целом, я не исключаю, что кому-то может понадобиться способ с проксированием запросов на свой бэк. Например, если у них нет куба, но есть стейджинг с поддержкой basic auth. Мб порт-форвардинг сделаем отдельным способом запуска?

2023-10-24 07:55 UTC, EduardZaydler commented
> В целом, я не исключаю, что кому-то может понадобиться способ с проксированием запросов на свой бэк. Например, если у них нет куба, но есть стейджинг с поддержкой basic auth. Мб порт-форвардинг сделаем отдельным способом запуска?

добавил отдельную команду

2023-10-25 06:54 UTC, sol-un approved these changes

2023-10-25 10:10 UTC, merged