Chore/pw e2e
moira-alert/web2.0 pull request #473
Opened 2023-12-29 09:29 UTC by EduardZaydler

2024-02-01 11:41 UTC, sol-un commented on playwright/e2eTests/triggerOperations.spec.ts
> +    ]);
Здесь лучше проверять, что бэкенд отработал корректно, и изменения сохранились) Выглядеть может как-то так:
```js
await triggerForm.submitButton("Save").click();
await expect(page).toHaveUrl(`/api/trigger/${testTriggerID}`); // проверяем, что нас перекинуло на страницу просмотра триггера
await expect(page.getByText(`${testTriggerName} changed`)).toBeVisible() // проверяем, что изменилось название триггера
await expect(page.getByText(`${testTriggerDescription} changed`)).toBeVisible() // проверяем, что изменилось описание триггера
```
Возможно, понадобится добавить ожидание ответа:
```js
const saveTriggerPromise = page.waitForResponse((response) => response.method() === 'PUT' && new RegExp(/api\/trigger/).test(response.url()));
await triggerForm.submitButton("Save").click()
await saveTriggerPromise;
... // дальше те же самые ассерты что выше
```
Но по идее без ожидания ответа должно сработать

2024-02-01 11:41 UTC, sol-un commented on playwright/e2eTests/teamsOperations.spec.ts
> +            await page.waitForResponse(/api\/teams/),
Также, не хватает проверок на то, что бэк отработал корректно, и изменения сохранились: `await expect(page.getByText(testTeamName)).toBeVisible()`

2024-02-01 11:41 UTC, sol-un commented on playwright/e2eTests/fixtures/addTriggerFixture.ts
> +    addTrigger: [
Мне кажется, лучше не добавлять в фикстуру код, который по сути является тестом. Предлагаю превратить это в тест на создание триггера, перенести в [triggerOperations.spec.ts](https://github.com/moira-alert/web2.0/pull/473/files#diff-f363345a9f5b32b574e6584f041ed65b674edc119f7e0c29c17b1d3e7f723ce6), [сконфигурировать](https://playwright.dev/docs/api/class-test#test-describe-configure) тест на последовательное выполнение (`test.describe.configure({ mode: 'serial' });`), а сами тесты расставить в нужном порядке (создание -> редактирование -> удаление)

2024-02-02 09:20 UTC, EduardZaydler commented on .github/workflows/e2e_tests.yml
> +        if: ${{ always() }}
делал для отладки ci, забыл поправить, исправил

2024-02-02 09:20 UTC, EduardZaydler commented on .github/workflows/unit-and-screenshot-tests.yml
>      runs-on: ubuntu-22.04
поправил

2024-02-02 09:20 UTC, EduardZaydler commented on playwright.config.ts
> +        baseURL: "http://localhost:9000",
бэк билдится так же с l[atest образами](https://github.com/moira-alert/moira/blob/master/docker-compose.yml), а с тестированием на нашем деве пришлось также плясать с бубном как и с сентрей

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/notificationsOperations.spec.ts
> +        notificationsPage.deliveryChannelItem(testChannelAccountName).click();
да, так и было задумано, но соглашусь, поправил

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/teamsOperations.spec.ts
> +        await expect(teamsPage.nameInput("Team name")).toHaveAttribute("value", testTeamName);
по другому не проверить что имя не сбросилось, если окажется проблемным местом - всегда можно выпилить

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/teamsOperations.spec.ts
> +            await page.waitForResponse(/api\/teams/),
имеет смысл, сделал

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
> +    await expect(triggerForm.simpleModeTab).toHaveAttribute("tabindex", "0");
это продиктовано одной из ошибок, когда при переходе на функ компоненты неправильно переключался стейт этих табов

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
> +        page.waitForEvent("popup"),
без этого не работало, надо переключать контекст между вкладками, потому что весь следующий код будет привязан к странице triggerInfo

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
> +    await clearTargetField(page, "testmetric".length);
хорошая идея, сделал

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
> +    ]);
добавил

2024-02-02 09:20 UTC, EduardZaydler commented on playwright/e2eTests/fixtures/addTriggerFixture.ts
> +    addTrigger: [
эта фикстура нужна не только для теста по операциям с триггерами, без нее не добавить подписки плюс в самой [доке](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures:~:text=await%20expect(page.getByTestId(%27result%27)).toHaveText(%27Success%27)%3B) все примеры сделаны по такому же принципу, плюс когда надо прогнать все тесты локально не придется делать все в один поток

2024-02-08 09:37 UTC, sol-un commented on playwright/e2eTests/triggerOperations.spec.ts
> +    await expect(triggerForm.simpleModeTab).toHaveAttribute("tabindex", "0");
Не нравится мне это, ну ладно, пусть будет)

2024-02-08 09:38 UTC, sol-un commented on playwright/e2eTests/triggerOperations.spec.ts
> +        page.waitForEvent("popup"),
Аа, тут потому что страница открывается в новой вкладке. Понял принял

2024-02-13 10:06 UTC, sol-un requested changes

2024-02-13 10:06 UTC, sol-un commented on playwright/e2eTests/notificationsOperations.spec.ts
> +    await page.waitForTimeout(1000);
Таймауты в тестах это антипаттерн, они могут приводить к нестабильным тестам. Лучше заменить на ожидание какого-то конкретного события, например ответ от бэка

2024-02-13 10:54 UTC, GreoGi commented on .github/workflows/e2e_tests.yml
> +        run: yarn test:e2e
У меня тут опасение, что >50% времени будет занимать установка зависимостей и Playwright'а
Тут на каждый запуск CI установка происходит?

Если можно как-то ускорить, будет круто
Из возможных варинтов:
- докер с предустановленной нодой и playwright'ом, но наверно ускорение не сильно большое будет
- Кэширование зависимостей фронта и установленного playwright'а

Но я хз возможно ли технически у вас это сделать в гитхабе

2024-02-13 10:56 UTC, GreoGi commented on playwright/e2eTests/notificationsOperations.spec.ts
> +});
И это по сути будет smoke тестом, что круто

2024-02-13 10:59 UTC, GreoGi commented on src/Stories/HighlightInput.stories.tsx
> +                    data-tid="0"
Сделай проп `data-tid` необязательным, тогда не нужно его в сторях задавать

2024-02-20 09:44 UTC, EduardZaydler commented on .github/workflows/e2e_tests.yml
> +        run: yarn test:e2e
зависимости кэшируются здесь 
![image](https://github.com/moira-alert/web2.0/assets/117674342/6ae76752-68bc-4209-b1fc-18944a6c5b6d)

2024-02-20 09:44 UTC, EduardZaydler commented on playwright/e2eTests/notificationsOperations.spec.ts
> +    await page.waitForTimeout(1000);
тк вынес в сетап, то и тест уже не нужен

2024-02-20 09:44 UTC, EduardZaydler commented on playwright/e2eTests/notificationsOperations.spec.ts
> +
добавил

2024-02-20 09:45 UTC, EduardZaydler commented on playwright/e2eTests/notificationsOperations.spec.ts
> +});
добавил

2024-02-20 09:45 UTC, EduardZaydler commented on .github/workflows/unit-and-screenshot-tests.yml
>            path: test-results
будут, меня устраивают нынешнение отчеты в виде трех скринов actual expected diff
![image](https://github.com/moira-alert/web2.0/assets/117674342/83434aba-6a46-424b-bdcc-42374668f3d0)

2024-02-20 10:09 UTC, sol-un requested changes

2024-02-20 10:09 UTC, sol-un commented on playwright/e2eTests/global.teardown.ts
> +    await clearDatabase();
Предлагаю здесь делать прямой запрос в апи, как и в setup-сценарии. Таким образом, мы отвяжем тесты от специфики бэкенда (для тестов не должно быть важно, используется там редис или какой-то другой способ хранения данных). Файл `utils`, таким образом, можно будет удалить вместе со старыми тестами. Также, можно удалить `puppeteer` и остальные зависимости, которые в них использовались)

2024-02-20 11:35 UTC, EduardZaydler commented on playwright/e2eTests/global.teardown.ts
> +    await clearDatabase();
поправил

2024-02-20 11:36 UTC, sol-un approved these changes

2024-02-21 04:23 UTC, merged