feat/informative tag stats page
moira-alert/web2.0 pull request #491
Opened 2024-03-22 12:37 UTC by EduardZaydler

# PR Summary

Additional information

Closes/Relates #issue

2024-03-22 12:41 UTC, EduardZaydler commented
/build

2024-03-25 05:24 UTC, EduardZaydler commented
/build

2024-03-25 10:12 UTC, sol-un requested changes

2024-03-25 10:12 UTC, sol-un commented on src/hooks/useSortData.tsx
Количество разных сортировок в Мойре начинает превышать разумные пределы)

[Сортировка паттернов](https://github.com/moira-alert/web2.0/blob/feature/informative_tag_stats_page/src/Containers/PatternListContainer.tsx#L81)
[Сортировка метрик](https://github.com/moira-alert/web2.0/blob/feature/informative_tag_stats_page/src/helpers/sort-metrics.ts)
[Какая-то еще сортировка через лодаш в мобильной версии](https://github.com/moira-alert/web2.0/blob/feature/informative_tag_stats_page/src/Components/Mobile/MobileTagSelectorPage/MobileTagSelectorPage.tsx#L36)

Было бы круто завести отдельную задачу на упорядочивание всех этих реализаций. В идеале, свести все к использованию лодаш без своих велосипедов)

2024-03-25 10:12 UTC, sol-un commented on src/Domain/Tag.ts
> +};
Я не думаю, что это относится к доменной области. Скорее это информация об особенностях интерфейса, которая к тому же привязана к тому, как сделана сейчас виртуализация списка. Предложил бы перенести это все в компонент TagList)

2024-03-25 10:12 UTC, sol-un commented on src/Components/TagListItem/TagListItem.tsx
> +    const isSubscriptions = subscriptions.length !== 0;
Здесь можно немного улучшить нейминг:
`showInfo` -> `isInfoVisible`
`setShowInfo` -> `setIsInfoVisible`
`isSubscriptions` -> `hasSubscriptions`

2024-03-26 05:31 UTC, FonDumik commented on src/Components/TagList/TagList.tsx
> +    const sortingIcon =
Название компонента лучше бы с большой начинать

2024-03-26 05:31 UTC, FonDumik commented on src/Components/TagListItem/TagListItem.tsx
> +                    onCancel={() => closeModal()}
А почему через стрелку, разве нельзя просто `{closeModal}`?

2024-03-26 05:31 UTC, FonDumik commented on src/Components/TagListItem/TagListItem.tsx
> +    const isSubscriptions = subscriptions.length !== 0;
Мне кажется, `set...` для булевых значений не очень подходит, лучше тогда уж `toggleInfoVisible`

2024-03-26 06:03 UTC, sol-un commented on src/Components/TagListItem/TagListItem.tsx
> +    const isSubscriptions = subscriptions.length !== 0;
Ну, называть значения в кортеже из `useState` как `[something, setSomething]` это конвенция, которая зафиксирована даже в документации к реакту) Правда там у них при названии булевых значений не соблюдается конвенция по называнию самих булевых значений (там пример `const [liked, setLiked] = useState(true);`). Но я обычно соблюдаю обе эти конвенции)

2024-03-26 07:16 UTC, EduardZaydler commented on src/Components/ContactSelect/ContactSelect.tsx
>      getContactsForComboBox = async (
не обратил внимания на пропсы, взял из примера строчкой ниже твоего, спасибо

2024-03-26 07:16 UTC, EduardZaydler commented on src/hooks/useSortData.tsx
соглы, заведу задачку

2024-03-26 07:17 UTC, EduardZaydler commented on src/Domain/Tag.ts
> +};
ок, перенес

2024-03-26 07:17 UTC, EduardZaydler commented on src/Components/TagListItem/TagListItem.tsx
> +    const isSubscriptions = subscriptions.length !== 0;
хоть это носит рекомендательный характер, соглашусь что `set` помогает понимать, что переменная 'x' отвечает за обновление 'x', остановлюсь на нем

2024-03-26 07:17 UTC, EduardZaydler commented on src/Components/TagList/TagList.tsx
> +    const sortingIcon =
ок, сделал

2024-03-26 07:17 UTC, EduardZaydler commented on src/Components/TagListItem/TagListItem.tsx
> +                    onCancel={() => closeModal()}
можно, сделал

2024-03-26 07:44 UTC, sol-un commented on src/Components/ContactSelect/ContactSelect.tsx
>      getContactsForComboBox = async (
Пожалуйста) Стало намного лучше, но есть еще пара моментов:

- ф-цию `renderTotalCount` на 103 строке можно убрать, она теперь нигде не используется
- в пропе `renderTotalCount` на 73 строке можно убрать обертку `MenuFooter`, она должна сама подставляться к возвращаемой строке (по крайней мере, в документации подставляется)

2024-03-26 07:47 UTC, sol-un commented
А вот еще я по описанию МРа так понимаю, что ты добавлял какие-то фичи:

> _added an ability to change the subscription_
> _added scrollToRow input for better navigation_

-- не надо ли к ним дописать e2e-тесты?

2024-03-26 07:56 UTC, EduardZaydler commented
> А вот еще я по описанию МРа так понимаю, что ты добавлял какие-то фичи:
> 
> > _added an ability to change the subscription_
> > _added scrollToRow input for better navigation_
> 
> -- не надо ли к ним дописать e2e-тесты?

эта страница будет закрыта админскими правами, пока со стороны бэкенда это только доезжает, тесты не будут работать, ближе к готовому результату уже можно будет подумать как разделить тесты на админские и нет и добавить соответствующие

2024-03-26 07:58 UTC, sol-un commented
> > А вот еще я по описанию МРа так понимаю, что ты добавлял какие-то фичи:
> > > _added an ability to change the subscription_
> > > _added scrollToRow input for better navigation_
> > 
> > 
> > -- не надо ли к ним дописать e2e-тесты?
> 
> эта страница будет закрыта админскими правами, пока со стороны бэкенда это только доезжает, тесты не будут работать, ближе к готовому результату уже можно будет подумать как разделить тесты на админские и нет и добавить соответствующие

Понял, вопрос снимается)

2024-03-26 08:00 UTC, EduardZaydler commented on src/Components/ContactSelect/ContactSelect.tsx
>      getContactsForComboBox = async (
да, действительно, сделал

2024-03-26 08:03 UTC, sol-un approved these changes

2024-03-26 09:10 UTC, FonDumik approved these changes

2024-03-28 08:38 UTC, merged