Feature/subscription sortings
moira-alert/web2.0 pull request #493
Opened 2024-03-28 08:42 UTC by EduardZaydler

# PR Summary

Additional information

Closes/Relates #issue

2024-03-28 08:42 UTC, EduardZaydler commented
/build

2024-03-29 11:00 UTC, EduardZaydler commented
/build

2024-04-01 11:40 UTC, GreoGi requested changes

2024-04-01 11:40 UTC, GreoGi commented on src/Components/SubscriptionList/SubscriptionList.less
> +    color: #666;
Пока у вас Мойра не сильно большая это не страшно, но в целом цвета всякие лучше уносить в css переменные и их использовать, так:
- Убираем дублирование и антипатерн "Магическая строка/число"
- Собираем все цвета в одном месте, проще управлять и понимать что вообще по проекту используется

2024-04-01 11:40 UTC, GreoGi commented on src/Components/SubscriptionList/SubscriptionList.less
> +}
Пробежись по css в проекте, вангую что не первый раз где стандартные стили кнопок сбрасывают.

Можно вынести в utility класс какой-нибудь и либо через less здесь mixin'ы делать, либо в вёрстке на саму кнопку 2 класса вешать.

Но в целом не сильно важно, можно забить

2024-04-01 11:40 UTC, GreoGi commented on src/Containers/SubscriptionListContainer/Components/FilterSubscriptionButtons.tsx
> +    return { FilterButtons, filteredSubscriptions };
Получается что это у тебя не  `Components/FilterSubscriptionButtons` должен быть, а как `hooks/useFilterSubscriptionButtons`

Я не очень люблю хуки с jsx вёрсткой внутри, но хз как тут легко переделать, пусть будет

2024-04-02 05:44 UTC, FonDumik commented on src/Components/SubscriptionList/SubscriptionList.less
> +}
Ещё вариант сразу в корневом css какие-то normalize свойства прописать

2024-04-02 05:58 UTC, FonDumik commented on src/Components/SubscriptionList/SubscriptionList.tsx
> +                            <button
А почему не Button из react-ui?

2024-04-02 05:58 UTC, FonDumik commented on src/Containers/SubscriptionListContainer/Components/FilterSubscriptionButtons.tsx
> +    return { FilterButtons, filteredSubscriptions };
Не, возвращать верстку из хука - ну такое

Лучше попилить этот модуль и вытащить в `/hooks` то, что связано с `filteredSubscriptions`, а здесь сразу возвращать jsx и использовать как компонент

2024-04-02 14:03 UTC, EduardZaydler commented on src/Components/SubscriptionList/SubscriptionList.tsx
> +                            <button
в треде выше видно что все равно все стили сбрасываются, решил оставить нативный <button>

2024-04-02 14:03 UTC, EduardZaydler commented on src/Containers/SubscriptionListContainer/Components/FilterSubscriptionButtons.tsx
> +    return { FilterButtons, filteredSubscriptions };
первоначальный вариант такой и был, но смутило большое количество пропсов, вернул в хук useFilterSubscriptions

2024-04-02 14:03 UTC, EduardZaydler commented on src/Components/SubscriptionList/SubscriptionList.less
> +    color: #666;
согласен, хотел сделать это привести все в нормальный вид отдельным ПРом, но вынес

2024-04-03 09:55 UTC, FonDumik approved these changes

2024-04-03 09:58 UTC, merged