Feat/contacts admin actions
moira-alert/web2.0 pull request #515
Opened 2024-06-06 05:37 UTC by EduardZaydler

# PR Summary

Additional information

Closes/Relates #issue

2024-06-06 06:31 UTC, EduardZaydler commented
/build

2024-06-20 08:01 UTC, EduardZaydler commented
/build

2024-06-24 08:37 UTC, EduardZaydler commented
/build

2024-06-24 10:40 UTC, EduardZaydler commented
/build

2024-06-25 09:44 UTC, GreoGi requested changes

2024-06-25 09:44 UTC, GreoGi commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +export const rtkQueryErrorAndLoadingHandler: Middleware = (api: MiddlewareAPI) => (next) => (
А можешь добавить коммент с описанием, что это за штука, для чего нужна, как работает
Выглядит как архитектурное решение, лучше расписать чуть подробнее

2024-06-25 09:44 UTC, GreoGi commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +};
В этом подходе с подсчётом происходящих прямо сейчас запросов меня смущает это:
- А что если есть поллинг данных (переодически отсылаются запросы на бэк), тогда страница постоянно будет в состоянии загрузки
- А что если есть подгружаемые данные в выпадающих списках. всю страницу уведём в состояние загрузки?
- В принципе не всегда нужно всю страницу уводить в состояние загрузки, а только её небольшую часть

2024-06-25 09:44 UTC, GreoGi commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +};
В общем много ограничений на приложение такой подход накладывает

2024-06-25 09:44 UTC, GreoGi commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +
Тут в теории несколько if'ов могут исполнится, нужно внимательно этот момент проверить.
Ещё сложно понять условия, почему они такие и что означают.
Если возможно, вынеси условия в константы с читаемым названием

2024-06-25 09:44 UTC, GreoGi commented on src/services/SubscriptionsApi.ts
> +                }
Тут return'ы одинаковые, т.е. условие тогда смысла не имеет

2024-06-25 09:44 UTC, GreoGi commented on src/services/SubscriptionsApi.ts
> +                }
Выше в файле ещё 1 такой случай

2024-06-25 09:44 UTC, GreoGi commented on src/services/ContactApi.ts
> +                }
Тут else конструкция не нужна. Можно сразу делать `return ["Contacts", "UserSettings"];`

2024-06-25 09:44 UTC, GreoGi commented on src/hooks/useLoadSettingsData.tsx
> +    }
Тут можно убрать let сделав просто 
```ts
const team =  teamId && teams?.teams.find((teamOverview) => teamOverview.id === teamId);
```

2024-06-25 09:44 UTC, GreoGi commented on src/desktop.bundle.tsx
> +const PrivateRoute = ({ component: Component, ...rest }: PrivateRouteProps) => {
А давай в отдельный файл вынесем PrivateRoute?

2024-06-25 09:44 UTC, GreoGi commented on src/Domain/Contact.ts
> +    }
1. ещё есть `contactType === "phone"` а в проверке его не вижу. Почему его нет?
2. else if :boom:
3. Я хз, но возможно стоит тут регулярки использовать вместо завязки на колво вбитых символов. Потому что вдруг пробелы ставили, аля `"+7 950 555 22 22"`

2024-06-25 12:53 UTC, sol-un requested changes

2024-06-25 12:53 UTC, sol-un commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const handleUpdateContact = async (testAfterUpdate?: boolean): Promise<void> => {
Избавиться от проп-дриллинга -- это верный шаг на пути к тому, чтобы снизить [зацепление](https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D1%86%D0%B5%D0%BF%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)) компонентов между собой.

Но можно пойти дальше: снизить зацепление между самими компонентами и пользовательскими сценариями приложения. Для этого можно `handleUpdateContact` сделать отдельной ф-цией. Все, что  сейчас в ней берется из замыкания компонента, можно передавать аргументами в замыкание этой отдельной ф-ции. Итоговый результат может выглядеть как-то так:
```javascript
export const useUpdateContact = (validationContainer, onCancel) => {
    const [updateContact, { isLoading: isUpdating }] = useUpdateContactMutation();
    const [testContact, { isLoading: isTesting }] = useTestContactMutation();

    const updateContact = (testAfterUpdate) => { ... }
    return { updateContact, isUpdating, isTesting };
}
```
Что это дает?
1. Проще разбираться, какая часть кода за что отвечает
2. При дальнейших доработках, проще искать код, отвечающий за конкретные сценарии
3. Один сценарий можно переиспользовать из разных мест в интерфейсе
4. Абстракция ограничивает распространение изменений по коду в будущем

Вот [пример](https://git.skbkontur.ru/infrastructure/slomon/-/blob/master/src/WebUI/ClientApp/src/application/slo/deleteSlo.ts?ref_type=heads) реализации этого паттерна в сломоне.

2024-06-25 12:53 UTC, sol-un commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const [error, setError] = useState<string | null>(null);
Можно использовать флаг `isError`, который предоставляют mutation-хуки RTK Query)

2024-06-25 12:53 UTC, sol-un commented on src/Components/CreateSubscriptionModal/CreateSubscriptionModal.tsx
> +    const isPlottingDefaultOn =
См. выше про [createEntityAdapter](https://redux-toolkit.js.org/usage/usage-guide#using-selectors-with-createentityadapter)

2024-06-25 12:53 UTC, sol-un commented on src/Components/CreateSubscriptionModal/CreateSubscriptionModal.tsx
> +        setError(null);
См. выше про флаг `isError` из RTKQ

2024-06-25 12:53 UTC, sol-un commented on src/Components/CreateSubscriptionModal/CreateSubscriptionModal.tsx
> +    const handleCreate = async (testAfterCreation?: boolean): Promise<void> => {
См. выше про расцепление компонентов с пользовательскими сценариями

2024-06-25 12:53 UTC, sol-un commented on src/Components/NewContactModal/NewContactModal.tsx
См. комментарии выше, к этому модулю тоже относится)

2024-06-25 12:53 UTC, sol-un commented on src/Components/SubscriptionEditModal/SubscriptionEditModal.tsx
См. выше

2024-06-25 12:53 UTC, sol-un commented on src/services/ContactApi.ts
> +                }
`return ["Contacts", isTeamContact ? "TeamSettings" : "UserSettings"]`

2024-06-26 08:38 UTC, flizzzzzard commented on src/Components/ContactList/ContactList.tsx
> +                                {contacts.map((contact) => {
кажется, что можно сразу вместо contact написать { name, value, type, id }

2024-06-26 08:45 UTC, flizzzzzard commented on src/Components/NewContactModal/NewContactModal.tsx
> +        if (!(await validateForm()) || !contactInfo || !contactInfo.value || !contactInfo.type) {
можно вынести часть условия про contactInfo в отдельную переменную, назвать как-нибудь по типу isValidContactInfo и, возможно, переиспользовать в areActionButtonsDisabled?

2024-06-27 08:20 UTC, EduardZaydler commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +export const rtkQueryErrorAndLoadingHandler: Middleware = (api: MiddlewareAPI) => (next) => (
в общем, позволяет не обрабатывать ошибки и состояние загрузки локально, достаточно просто использовать данные в компонентах, хороший пример с хуком `useLoadSettingsData`, где для кучи запросов надо было составить монструозное выражение по типу `error = userError || userSettingsError || teamsSettingsError || teamsError...` , то же самое для состояния загрузки. Еще при инвалидации кеша тоже хотелось показывать лоадер, а не просто ререндер с новыми данными. Если надо обработать ошибки и загузку локально достаточно прокинуть {handleLoadingLocally, handleErrorLocally} в запросе

2024-06-27 08:20 UTC, EduardZaydler commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +};
1. поэтому я добавил программное управление этой фичей прокидыванием {handleLoadingLocally, handleErrorLocally} пропсов
2. тот же ответ, на странице teams как раз то, о чем ты говоришь (выпадашка с юзерами), я сейчас ее делаю и никаких проблем
3. если правильно понял, то ответ тот же)

2024-06-27 08:20 UTC, EduardZaydler commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +
повыносил, вроде попонятнее

2024-06-27 08:20 UTC, EduardZaydler commented on src/services/SubscriptionsApi.ts
> +                }
не одинаковые, немного упростил логику

2024-06-27 08:20 UTC, EduardZaydler commented on src/services/ContactApi.ts
> +                }
поправил

2024-06-27 08:20 UTC, EduardZaydler commented on src/hooks/useLoadSettingsData.tsx
> +    }
поправил

2024-06-27 08:20 UTC, EduardZaydler commented on src/desktop.bundle.tsx
> +const PrivateRoute = ({ component: Component, ...rest }: PrivateRouteProps) => {
вынес

2024-06-27 08:20 UTC, EduardZaydler commented on src/Domain/Contact.ts
> +    }
я не знаю зачем это в коде, просто перенес из старого, не особо задумывался, сейчас посмотрел и как будто это не нужно в принципе, регулярки прилетают из конфига вместе с плэйсхолдерами, значения валидируются по этим регуляркам, удалил

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/ContactEditForm/ContactEditForm.tsx
> +    const contactItems: Array<[ContactTypes, string]> = (config?.contacts ?? []).map((contact) => [
добавил селекторы

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/ContactEditForm/ContactEditForm.tsx
> +    };
завернул в usecallback

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/ContactEditForm/ContactEditForm.tsx
> +    const validateValue = useCallback((): ValidationInfo | null => {
вынес в отдельную, плюс переиспользовал

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const handleUpdateContact = async (testAfterUpdate?: boolean): Promise<void> => {
сделал

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const [error, setError] = useState<string | null>(null);
тут все завязано на том, что нужно выводить ошибку в модалке, дожидаться успешного выполнения запроса и только потом закрывать, без try catch модалка закроется даже если есть ошибка

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/CreateSubscriptionModal/CreateSubscriptionModal.tsx
> +    const isPlottingDefaultOn =
добавил селектор

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/CreateSubscriptionModal/CreateSubscriptionModal.tsx
> +    const handleCreate = async (testAfterCreation?: boolean): Promise<void> => {
сделал

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/NewContactModal/NewContactModal.tsx
расцепил

2024-06-27 08:20 UTC, EduardZaydler commented on src/Components/SubscriptionEditModal/SubscriptionEditModal.tsx
расцепил

2024-06-27 08:21 UTC, EduardZaydler commented on src/Components/ContactList/ContactList.tsx
> +                                {contacts.map((contact) => {
деструктурировал

2024-06-27 08:21 UTC, EduardZaydler commented on src/Components/NewContactModal/NewContactModal.tsx
> +        if (!(await validateForm()) || !contactInfo || !contactInfo.value || !contactInfo.type) {
вынес

2024-06-27 09:55 UTC, sol-un commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const [error, setError] = useState<string | null>(null);
Хмм, было бы круто обработку ошибок сделать централизованно через [мидлвару](https://redux-toolkit.js.org/rtk-query/usage/error-handling#handling-errors-at-a-macro-level), из которой показывать эту модалку. А то без этого приходится обрабатывать вручную в каждом сценарии + остается лишнее зацепление из-за передачи `setError` в хук. В сломоне, кстати, тоже я пока не сделал централизованное решение)

В общем ладно, МР и так уже большой + ты возможно еще не все переписал на RTKQ, поэтому пока пусть так будет)

2024-06-27 10:00 UTC, EduardZaydler commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const [error, setError] = useState<string | null>(null);
а я сделал, самое первое сообщение от Паши

2024-06-27 10:37 UTC, sol-un requested changes

2024-06-27 10:37 UTC, sol-un commented on src/Components/SubscriptionEditModal/SubscriptionEditModal.tsx
Здесь можно еще `handleDelete` вынести)

2024-06-27 10:37 UTC, sol-un commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const handleUpdateContact = async (testAfterUpdate?: boolean): Promise<void> => {
Очень круто 👍 Можно еще `handleDeleteContact` вынести)

2024-06-27 10:37 UTC, sol-un commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const [error, setError] = useState<string | null>(null);
А точно, получается можно вроде бы вручную не обрабатывать ошибки в отдельных сценариях) А просто в компоненте `ErrorModal` брать `error` из UI-стора вместо того, чтобы передавать его пропом

2024-06-28 04:27 UTC, EduardZaydler commented on src/Components/SubscriptionEditModal/SubscriptionEditModal.tsx
вынес

2024-06-28 04:27 UTC, EduardZaydler commented on src/Components/ContactEditModal/ContactEditModal.tsx
> +    const handleUpdateContact = async (testAfterUpdate?: boolean): Promise<void> => {
вынес

2024-06-28 08:06 UTC, GreoGi commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +};
Ага, я чот проглазел что есть обработка походов на сервер в обход этой глобальной миддлварки

2024-06-28 08:16 UTC, GreoGi commented on src/services/SubscriptionsApi.ts
> +                }
А, сорре, глаз замылился чот 😪

2024-06-28 08:26 UTC, GreoGi commented on src/services/ContactApi.ts
> +                }
Кажется что нет, у меня всё ещё гит старый код в этом месте показывает

![image](https://github.com/moira-alert/web2.0/assets/43406801/6de631af-b2c2-485d-b582-6e43b57f3bb4)

2024-06-28 08:27 UTC, GreoGi commented on src/desktop.bundle.tsx
> +const PrivateRoute = ({ component: Component, ...rest }: PrivateRouteProps) => {
Тоже не вижу, мб забыл в репу свои комиты запушить?

2024-06-28 08:29 UTC, GreoGi commented on src/services/rtkQueryErrorAndLoadingHandler.ts
> +
Всё ещё старый код

2024-06-28 08:31 UTC, EduardZaydler commented on src/services/ContactApi.ts
> +                }
если в ветку зайти, то свежак показывает, хз почему в ченжах нет
![image](https://github.com/moira-alert/web2.0/assets/117674342/cb697025-bd63-4dd9-958d-337aaeb00507)

2024-06-28 09:24 UTC, GreoGi approved these changes

2024-06-28 09:48 UTC, sol-un approved these changes

2024-07-01 03:23 UTC, flizzzzzard approved these changes

2024-07-01 03:27 UTC, merged