contact events noisiness stat
moira-alert/web2.0 pull request #526
Opened 2024-07-18 07:42 UTC by EduardZaydler

# PR Summary

Additional information

Closes/Relates #issue

2024-07-18 08:12 UTC, EduardZaydler commented
/build

2024-07-18 14:35 UTC, sol-un requested changes

2024-07-18 14:35 UTC, sol-un commented on src/Components/ContactList/Components/ContactEventsChart.tsx
> +    const options = {
Можно тоже унести из компонента и превратить в функцию `function getOptions(interval: EContactEventsInterval): ChartOptions<"bar">`

2024-07-18 14:35 UTC, sol-un commented on src/Components/ContactList/Components/TriggerEventsChart.tsx
> +    const groupedEvents = events.reduce<Record<string, number>>((acc, event) => {
`useMemo`?)

2024-07-18 14:35 UTC, sol-un commented on src/Components/ContactList/Components/TriggerEventsChart.tsx
> +    const options = {
Можно унести наружу, чтобы не пересоздавалось при каждом рендере

2024-07-18 14:35 UTC, sol-un commented on src/Components/ContactList/Components/htmlLegendPlugin.ts
> +        listContainer.style.maxWidth = "100%";
А можно здесь добавить класс, а стили в css унести? Ниже по коду еще есть аналогичные случаи, везде не буду комментировать)

2024-07-18 14:35 UTC, sol-un commented on src/Components/ContactList/ContactList.tsx
>      const renderEmptyListMessage = useCallback(
Есть какие-то причины так делать вместо того чтобы создать отдельный компонент `<EmptyListMessage onClick={openNewContactModal} />`?

2024-07-18 14:35 UTC, sol-un commented on src/helpers/DateUtil.ts
> +    return date;
Можно убрать промежуточную константу

2024-07-19 06:08 UTC, FonDumik commented on src/Components/ContactList/Components/htmlLegendPlugin.ts
> +        }
Может можно было бы обойтись без этого цикла, прописав что-то вроде `ul.innerHTML = ''` ?

2024-07-19 06:08 UTC, FonDumik commented on src/Components/ContactList/Components/htmlLegendPlugin.ts
> +                boxSpan.style.borderColor = item.strokeStyle as string;
Частое `as` - всё равно, что использование `any`. Согласен с Андреем, что лучше это всё вынести в стили отдельно и не задавать постоянно руками

2024-07-19 06:08 UTC, FonDumik commented on src/Components/ContactList/Components/htmlLegendPlugin.ts
> +                const li = document.createElement("li");
Тут прям нативный js: создание элемента, указание его стилей, навешивание onclick.
В проекте на react этот код вызывает смешанные чувства. Может перевести всё в tsx?

2024-07-22 06:52 UTC, EduardZaydler commented on src/Components/ContactList/Components/htmlLegendPlugin.ts
> +                const li = document.createElement("li");
причиной было то, что я не знал какие сайд эффекты может принести вызов reactDom.render несколько раз в приложении, решил написать как это сделано в доке chart js(html в назавании плагина как бы намекает на использовает на использование нативного js). сейчас потратил чуть больше времени на изучение, переписывание и тестирование и переписал

2024-07-22 06:52 UTC, EduardZaydler commented on src/Components/ContactList/Components/ContactEventsChart.tsx
> +        return events.reduce((acc, event) => {
сделал, немного подправил логику

2024-07-22 06:52 UTC, EduardZaydler commented on src/Components/ContactEventStats/ContactEventStats.tsx
> +    }, []);
чтобы выполнять запрос как по клику так и при рендере

2024-07-22 07:10 UTC, sol-un commented on src/Components/ContactEventStats/ContactEventStats.tsx
> +    }, []);
А все, увидел)

2024-07-22 07:32 UTC, sol-un approved these changes

2024-07-22 07:35 UTC, FonDumik approved these changes

2024-07-22 12:10 UTC, merged