fix/added execComand fallback
moira-alert/web2.0 pull request #537
Opened 2024-09-12 07:30 UTC by EduardZaydler

# PR Summary

Additional information

Closes/Relates #issue

2024-09-12 13:16 UTC, sol-un requested changes

2024-09-12 13:16 UTC, sol-un commented on src/Components/TriggerEditForm/Components/CopyButton.tsx
> +const pusfSuccessfulMessage = () => Toast.push("Text copied to clipboard");
```suggestion
const pushSuccessfulMessage = () => Toast.push("Text copied to clipboard");
```

2024-09-16 07:43 UTC, flizzzzzard approved these changes

2024-09-17 07:25 UTC, sol-un approved these changes

2024-09-18 03:54 UTC, merged