removed moiraapi class
moira-alert/web2.0 pull request #560
Opened 2024-11-18 06:36 UTC by EduardZaydler

# PR Summary

Additional information

Closes/Relates #issue

2024-11-18 06:58 UTC, EduardZaydler commented
/build

2024-11-18 07:18 UTC, EduardZaydler commented
/build

2024-11-22 09:16 UTC, sol-un requested changes

2024-11-22 09:16 UTC, sol-un commented on src/services/PatternsApi.ts
> +                }
Не раз видел в коде повторение вот этого паттерна. А он точно нужен? В документации к RTK Query явно не нашел подтверждения, но здравый смысл подсказывает, что как будто бы не будет вызываться метод `invalidatesTags`, если запрос вернул ошибку. Прописывать какое-то кастомное поведение надо для продвинутых случаев, типо как [в документации](https://redux-toolkit.js.org/rtk-query/usage/automated-refetching#providing-errors-to-the-cache), где в зависимости от статуса ошибки могут инвалидироваться разные теги

2024-12-03 06:49 UTC, EduardZaydler commented on src/services/PatternsApi.ts
> +                }
> что как будто бы не будет вызываться метод invalidatesTags

 будет, наткнулся сам на это раньше, поэтому и сделал

2024-12-03 06:49 UTC, EduardZaydler commented on src/Containers/TriggerEditContainer.tsx
> +                        dispatch(setIsSaveModalVisible(false));
да, я уже использовал это в тех местах где состояние влияет на другие части приложения или должно быть доступно глобально, кмк когда компонент сам контролирует своё состояние, это делает логику UI проще для понимания

2024-12-03 06:49 UTC, EduardZaydler commented on src/Containers/PatternListContainer.tsx
>      const removePattern = async (pattern: string) => {
убрал

2024-12-03 06:49 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +    const renderCounters = (): React.ReactElement => {
да, я завел тикет, компонент большой и делать в этом ПРе не хотелось

2024-12-03 06:49 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +        _.pickBy(metrics, (metric) => metric.state === status);
сделал

2024-12-03 06:49 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +    const getHasExceptionState = () => data.last_check?.state === Status.EXCEPTION;
поправил

2024-12-03 06:49 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +    );
убрал

2024-12-03 06:49 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +    }, []);
убрал

2024-12-03 06:49 UTC, EduardZaydler commented on playwright/pages/triggerInfo.page.ts
> +        this.triggerMaintenance = page.locator("[data-tid='TriggerMaintenanceButton']");
на странице две идентичных кнопки для триггера и метрики

2024-12-03 06:49 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
> +            ).toBeLessThanOrEqual(1);
тут, (скорее всего из-за ранней реализации, потому что сейчас все работает гут), были расхождения где-то на секунду, сделал toEqual. проверяется что триггер/метрика замьютятся на переданное значение, то есть то что было в старом тесте

2024-12-03 06:49 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
> +    });
поправил

2024-12-03 06:49 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
>      await page.waitForTimeout(1000);
для отладки наверное был, убрал

2024-12-03 06:53 UTC, EduardZaydler commented
/build

2024-12-03 08:31 UTC, sol-un commented on playwright/e2eTests/triggerOperations.spec.ts
> +            ).toBeLessThanOrEqual(1);
> _проверяется что триггер/метрика замьютятся на переданное значение_

Тогда я бы ограничился проверками на то, что появился соответствующий текст на странице. Которые на 84-89 строчках

2024-12-03 08:31 UTC, sol-un commented on playwright/pages/triggerInfo.page.ts
> +        this.triggerMaintenance = page.locator("[data-tid='TriggerMaintenanceButton']");
Можно поменять им тексты, чтобы они не были идентичными)

2024-12-03 09:38 UTC, flizzzzzard commented on src/Components/TriggerListItem/TriggerListItem.tsx
>          const hasExpression = data.expression != null && data.expression !== "";
вроде как можно заменить на `!!data.expression`

2024-12-03 09:41 UTC, flizzzzzard commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +                            {data.throttling !== 0 && (
не хватит чисто `data.throttling && (...)`? (много где сравнения с нулями, поэтому вопрос)

2024-12-03 09:45 UTC, flizzzzzard commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +const TriggerListItem: React.FC<Props> = ({ data, searchMode, onChange, onRemove, history }) => {
можно ниже деструктурировать типа `{ last_check, id, highlights, ... } = data`, вроде целиком нигде ее не используешь

2024-12-03 09:46 UTC, EduardZaydler commented on playwright/e2eTests/triggerOperations.spec.ts
> +            ).toBeLessThanOrEqual(1);
текст в селекте и текст после запроса отличаются, придется маппить, да и изначальный тест работал по такому сценарию

2024-12-03 09:49 UTC, flizzzzzard commented on src/Containers/TriggerAddContainer.tsx
> +const TriggerAddContainer = (props: RouteComponentProps) => {
`{ history }`?

2024-12-03 09:49 UTC, flizzzzzard commented on src/Containers/TriggerAddContainer.tsx
> +const TriggerAddContainer = (props: RouteComponentProps) => {
в плане вместо props

2024-12-03 09:56 UTC, flizzzzzard commented on src/pages/trigger-list/trigger-list.desktop.tsx
> +                        searchMode={searchText !== ""}
`searchMode={!!searchText}` можно попробовать

2024-12-03 09:59 UTC, flizzzzzard commented on src/pages/trigger-list/trigger-list.tsx
> +    const isTagParamEnabled = tags.length === 0 && localTags?.length;
`!tags.length === 0 && localTags?.length`?

2024-12-03 10:09 UTC, sol-un commented on playwright/e2eTests/triggerOperations.spec.ts
> +            ).toBeLessThanOrEqual(1);
> _текст в селекте и текст после запроса отличаются_

Именно по изменениям текста тесты должны "понять", что запрос завершился успешно) Такой подход к тестированию [рекомендуется](https://playwright.dev/docs/best-practices#test-user-visible-behavior) в документации. Ну ладно, это то как я бы сделал, ты кароч сам решай)

2024-12-03 10:13 UTC, sol-un commented on playwright/pages/triggerInfo.page.ts
> +        this.triggerMaintenance = page.locator("[data-tid='TriggerMaintenanceButton']");
> _в чем тогда разница менять интерфейс и делать уникальный текст или просто поставить уникальный атрибут_

В первом случае тесты будут ближе к тому, как пользователь взаимодействует с приложением. Пользователь выбирает элементы интерфейса не по атрибутам, а глядя на тексты интерфейса) Приближать поведение тестов к пользовательскому это еще один рекомендованный подход, подробнее -- в [документации к testing-library](https://testing-library.com/docs/queries/about/#priority)

В общем, тоже сам решай)

2024-12-03 10:13 UTC, sol-un approved these changes

2024-12-03 10:22 UTC, EduardZaydler commented on src/pages/trigger-list/trigger-list.tsx
> +    const isTagParamEnabled = tags.length === 0 && localTags?.length;
тут все правильно, сравниваются тэги из адресной строки и тэги в локалсторадже, если нет первых то берем из локалстораджа

2024-12-03 10:22 UTC, EduardZaydler commented on src/pages/trigger-list/trigger-list.desktop.tsx
> +                        searchMode={searchText !== ""}
ага

2024-12-03 10:23 UTC, EduardZaydler commented on src/Containers/TriggerAddContainer.tsx
> +const TriggerAddContainer = (props: RouteComponentProps) => {
заюзал usehistory

2024-12-03 10:23 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +const TriggerListItem: React.FC<Props> = ({ data, searchMode, onChange, onRemove, history }) => {
я выше писал что завел тикет на разбить этот компонент на поменьше, сейчас же просто переписал на функциональный чтобы юзать хуки, предлагаю все там сделать

2024-12-03 10:23 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
> +                            {data.throttling !== 0 && (
если будет цифра !==0 она и отрендерится

2024-12-03 10:23 UTC, EduardZaydler commented on src/Components/TriggerListItem/TriggerListItem.tsx
>          const hasExpression = data.expression != null && data.expression !== "";
поправил

2024-12-04 04:04 UTC, merged