Feat/dark theme
moira-alert/web2.0 pull request #562
Opened 2024-11-28 08:32 UTC by EduardZaydler

# PR Summary

Additional information

Closes/Relates #issue

2024-11-28 08:34 UTC, EduardZaydler commented
/build

2024-12-02 07:38 UTC, EduardZaydler commented
/build

2024-12-02 07:43 UTC, EduardZaydler commented
/build

2024-12-02 08:41 UTC, EduardZaydler commented
/build

2024-12-02 11:10 UTC, FonDumik commented on src/Components/ContactList/ContactList.tsx
> +                        <ContactTypeIcon type={type} />
В компоненте `ContactTypeIcon` у тебя рендерится `<IconComponent color={theme.textColorDefault} size={16} />` - для `theme.textColorDefault` это похоже на дублирование кода

2024-12-02 11:10 UTC, FonDumik commented on src/Components/Header/Header.less
>          color: #fff !important;
Тут, получается, можно использовать цвета из `variables.less`

2024-12-02 11:10 UTC, FonDumik commented on local_modules/styles/variables.less
> +    --icon-hover-color: black;
`#000`

2024-12-03 05:03 UTC, EduardZaydler commented on local_modules/styles/mixins.less
> +    padding: 6px 8px 6px 8px;
поправил

2024-12-03 05:03 UTC, EduardZaydler commented on local_modules/styles/variables.less
> +    --inverted: #151515;
кмк таким удобно пользоваться на старте проекта, а не когда уже все обросло своими специфичными оттенками. это же весь код надо перелопатить и еще скриншоты обновить

2024-12-03 05:03 UTC, EduardZaydler commented on src/Components/ContactList/ContactList.tsx
> +                        <ContactTypeIcon type={type} />
ага, убрал

2024-12-03 05:03 UTC, EduardZaydler commented on src/Components/Header/Header.less
>          color: #fff !important;
поправил

2024-12-03 05:03 UTC, EduardZaydler commented on local_modules/styles/variables.less
> +    --icon-hover-color: black;
поправил

2024-12-04 06:25 UTC, FonDumik submitted a review, later dismissed

2024-12-04 13:22 UTC, GreoGi commented
Было бы круто если в сторибуке тоже можно было бы тему переключать.
Сейчас это вроде не сделано, предлагаю отдельный тикет завести под это, а то зная сторибук там могут быть танцы с бубном

2024-12-04 13:32 UTC, GreoGi commented
Ещё предлагаю завести тикет на добавление скриншотных тестов для тёмной темы

2024-12-04 14:07 UTC, GreoGi requested changes

2024-12-04 14:11 UTC, GreoGi commented on src/desktop.bundle.tsx
> +        >
И таких мест много

2024-12-05 09:59 UTC, GreoGi commented on src/Components/MetricListItem/MetricListItem.tsx
> +    const [hover, setHover] = useState(false);
Вот так пихать hover в стэйт вообще не хорошо, раз в 10 повышаешь нагрузку на браузер.

Всё ещё предлагаю сразу в css использовать переменные темы, а не идти через цепочку\
`css переменные` -> `переопределение react-ui темы` -> `хук использования темы` -> `вставка в style проп через js внутри компонентов`

Ты завязался на тему react-ui по всей мойре, но лучше для обычных компонентов не из библиотеки напрямую в их css использовать css переменные.
Потому что если вдруг гипотетически захочется сменить библиотеку компонентов, придётся ещё и темизацию переделывать.

Крч если коротко - зазря завязался на react-ui тему, оставь её только для переопределения react-ui компонентов

2024-12-06 09:39 UTC, EduardZaydler commented
/build

2024-12-06 09:52 UTC, EduardZaydler commented on src/Components/MetricListItem/MetricListItem.tsx
> +    const [hover, setHover] = useState(false);
перешел на переменные, тикеты на сторибук и скриншоты завел

2024-12-06 09:52 UTC, EduardZaydler commented on src/hooks/themes/useTheme.ts
> +import { AddonsThemeIn } from "@skbkontur/react-ui-addons";
ок, убрал

2024-12-06 09:52 UTC, EduardZaydler commented on src/hooks/themes/useIsBrowserPrefersDarkTheme.ts
> +export const useIsBrowserPrefersDarkTheme = () => {
удолил

2024-12-06 09:52 UTC, EduardZaydler commented on src/desktop.bundle.tsx
> +        >
соглы, перешел на css где это возможно

2024-12-06 10:15 UTC, GreoGi approved these changes

2024-12-09 03:34 UTC, merged